name: danger_plugin_dart_analyze
description: A Danger Dart plugin to process analyze result.
version: 1.0.0
homepage: https://github.com/blendthink/danger-plugin-dart-analyze
repository: https://github.com/blendthink/danger-plugin-dart-analyze
documentation: https://github.com/blendthink/danger-plugin-dart-analyze
issue_tracker: https://github.com/blendthink/danger-plugin-dart-analyze/issues

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  danger_core: ^1.0.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
